# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
development:
  adapter: postgresql
  database: runonrails
  pool: 5
  timeout: 5000

staging:
  adapter: postgresql
  database: staging
  pool: 5
  timeout: 5000
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

production:
  adapter: postgresql
  database: production
  pool: 5
  timeout: 5000
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>