# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b289e4b6350e3693c76f3ecf2817150f1b48998eb4ebc31e9abb0068526711fe637e792c6600798cf6474a2b5faef9ba2db6cdc838d8a559768a586c64645e4a

test:
  secret_key_base: 76d42120e4b3b9d7d13094d979cb9e8dad6e6a52362ae82dcabf6b6f100ef0e1ed77b1bcb9c4507b3b08e656077d36e2322728dfe4300a8068268aa4d1ee8995

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
